# Generated by Django 3.2.8 on 2021-10-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': '"raw_data"."stock"',
            },
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ratio', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raw_data.stock')),
            ],
            options={
                'db_table': '"raw_data"."stock_split"',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raw_data.stock')),
            ],
            options={
                'db_table': '"raw_data"."stock_price"',
            },
        ),
        migrations.CreateModel(
            name='StockFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('filename', models.TextField()),
                ('url', models.URLField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raw_data.stock')),
            ],
            options={
                'db_table': '"raw_data"."stock_filing"',
            },
        ),
        migrations.CreateModel(
            name='StockDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_date', models.DateField()),
                ('ex_dividend_date', models.DateField()),
                ('payout_date', models.DateField()),
                ('amount', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raw_data.stock')),
            ],
            options={
                'db_table': '"raw_data"."stock_dividend"',
            },
        ),
    ]
