# Generated by Django 3.2.8 on 2022-01-22 08:00

# pylint: disable=missing-module-docstring, invalid-name, missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raw_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdividend",
            options={"ordering": ["payout_date"]},
        ),
        migrations.AlterModelOptions(
            name="stockprice",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="stocksplit",
            options={"ordering": ["date"]},
        ),
    ]
