# Generated by Django 4.0.4 on 2022-05-04 11:48

# pylint: disable=missing-module-docstring, invalid-name, missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raw_data", "0002_auto_20220122_0800"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdividend",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="stockdividend",
            old_name="payout_date",
            new_name="date",
        ),
    ]
