# Generated by Django 3.2.8 on 2022-01-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20211122_1343"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashtransaction",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="forextransaction",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="stocktransaction",
            options={"ordering": ["date"]},
        ),
    ]
