# Generated by Django 3.2.8 on 2022-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_auto_20211122_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Software", "Software"),
                    ("Hardware", "Hardware"),
                    ("Media", "Media"),
                    ("Telecommunication", "Telecommunication"),
                    ("Health care services", "Health Care Services"),
                    ("Consumer services", "Consumer Services"),
                    ("Business services", "Business Services"),
                    ("Financial services", "Financial Services"),
                    ("Consumer goods", "Consumer Goods"),
                    ("Industrial materials", "Industrial Materials"),
                    ("Energy", "Energy"),
                    ("Utilities", "Utilities"),
                    ("Real estate", "Real Estate"),
                    ("ETF", "Etf"),
                ],
                max_length=20,
            ),
        ),
    ]
