# Generated by Django 4.0.4 on 2022-05-28 20:31

# pylint: disable=missing-module-docstring, invalid-name, missing-class-docstring

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_stock_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockWatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="stocks.stock"
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockwatchlist",
                    ),
                ),
            ],
            options={
                "db_table": '"stocks"."stock_watchlist_item"',
            },
        ),
        migrations.CreateModel(
            name="TargetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watchlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockwatchlistitem",
                    ),
                ),
            ],
            options={
                "db_table": '"stocks"."target_price"',
            },
        ),
        migrations.CreateModel(
            name="PositionSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.FloatField()),
                ("description", models.TextField(null=True)),
                ("at_cost", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watchlist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockwatchlistitem",
                    ),
                ),
            ],
            options={
                "db_table": '"stocks"."position_size"',
            },
        ),
        migrations.AddConstraint(
            model_name="stockwatchlistitem",
            constraint=models.UniqueConstraint(
                fields=("watchlist", "stock"), name="unique item"
            ),
        ),
    ]
