# Generated by Django 4.0.4 on 2022-06-05 07:38

# pylint: disable=missing-module-docstring, invalid-name, missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_stockwatchlistitem_targetprice_positionsize_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionsize",
            name="description",
        ),
        migrations.RemoveField(
            model_name="targetprice",
            name="description",
        ),
        migrations.AddField(
            model_name="positionsize",
            name="name",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="targetprice",
            name="name",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
    ]
