name: Staging CD

on:
  push:
    branches: [master]

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: horvathmarton/stock-buddy-api:staging
          file: Dockerfile.prod

  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: push-image
    steps:
      - run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - run: ssh -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_IP }} -t "docker rm -f stock-buddy-staging-api 2> /dev/null || true"
      - run: ssh -i ~/.ssh/id_rsa ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_IP }} -t "docker run --pull always --net host -it --env-file ./env --name=stock-buddy-staging-api -d horvathmarton/stock-buddy-api:staging"
